#!/usr/bin/env perl

# Copyright (c) 2024  Teddy Wing
#
# This file is part of Eduquote.
#
# Eduquote is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Eduquote is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Eduquote. If not, see <https://www.gnu.org/licenses/>.


=head1 NAME

eduquote - Convert straight quotes to typographer's quotes

=head1 SYNOPSIS

eduquote [options] [file...]

Options:

  -h, --help    print help
  -V, --version show the program version

=head1 DESCRIPTION

Convert straight quotes in the input into typographer's quotes. If no file
argument is given, reads from standard input.

Assumes UTF-8.

=head1 OPTIONS

=over 8

=item -h, --help

Print usage help.

=item -V, --version

Print the program version.

=back

=cut


use strict;
use warnings;
use v5.10;

use Getopt::Long;
use Pod::Usage;

use constant {
	VERSION => '0.0.1',
};

my $opt_help = 0;
my $opt_version = 0;

GetOptions(
	'h|help' => \$opt_help,
	'V|version' => \$opt_version,
)
	or die('argument error');

if ($opt_help) {
	pod2usage(-verbose => 0, -exitval => 0);
}

if ($opt_version) {
	say VERSION;
	exit;
}

while (<<>>) {
	my $line = $_;
	$line =~ s/(\S)"/$1”/g;
	$line =~ s/"/“/g;
	$line =~ s/(\S)'/$1’/g;
	$line =~ s/'/‘/g;

	print $line;
}
